version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - auth-service
      - landing-page
      - hello-world-app

  auth-service:
    build: ./auth-service
    environment:
      - PORT=3001
      - SESSION_SECRET=dev-secret-key-change-in-production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - BASE_URL=https://kl-pi.tail9f5728.ts.net
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./auth-service/data:/app/data
    networks:
      - app-network

  landing-page:
    build: ./landing-page
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - HELLO_WORLD_URL=http://hello-world-app:3002
      - CHAT_APP_URL=http://localhost:3003
      - BASE_URL=https://kl-pi.tail9f5728.ts.net
    depends_on:
      - auth-service
    networks:
      - app-network

  hello-world-app:
    build: ./hello-world-app
    environment:
      - PORT=3002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth-data:
  caddy_data:
  caddy_config:
