// Garmin Connect API Integration Service using garmin-connect library
// This service handles authentication and workout creation/sync with Garmin Connect

const { GarminConnect } = require('garmin-connect');

class GarminConnectService {
    constructor() {
        this.client = null;
        this.isAuthenticated = false;
    }

    /**
     * Authenticate with Garmin Connect using username/password
     * @param {string} username - Garmin Connect username
     * @param {string} password - Garmin Connect password
     * @returns {Promise<boolean>} - Authentication success
     */
    async authenticate(username, password) {
        try {
            console.log('🔐 Authenticating with Garmin Connect using library...');
            
            // Create new client instance
            this.client = new GarminConnect({
                username: username,
                password: password
            });

            // Perform login
            await this.client.login();
            this.isAuthenticated = true;
            
            console.log('✅ Successfully authenticated with Garmin Connect');
            return true;

        } catch (error) {
            console.error('❌ Garmin Connect authentication failed:', error.message);
            this.isAuthenticated = false;
            return false;
        }
    }

    /**
     * Create a running workout using the library's built-in method
     * @param {Object} workoutData - Workout configuration
     * @returns {Promise<Object>} - Created workout data
     */
    async createRunningWorkout(workoutData) {
        if (!this.isAuthenticated || !this.client) {
            throw new Error('Not authenticated with Garmin Connect');
        }

        try {
            console.log('🏃 Creating running workout using library...');

            const {
                name = 'Training Workout',
                description = 'Generated by Training Peaks Service',
                distance = 5000, // meters
                paceMinSlow = '5:00', // min:sec per km
                paceMaxFast = '5:10' // min:sec per km
            } = workoutData;

            console.log(`📝 Creating workout: ${name}`);
            console.log(`📏 Distance: ${distance}m`);
            console.log(`⏱️ Target pace: ${paceMaxFast}-${paceMinSlow} per km`);
            console.log(`📄 Description: ${description}`);

            // Get workout count before creation
            const workoutsBefore = await this.getWorkoutCount();
            console.log(`📋 Workouts before creation: ${workoutsBefore}`);

            // Use the library's addRunningWorkout method
            const result = await this.client.addRunningWorkout(name, distance, description);

            console.log('✅ Workout created successfully with library!');
            console.log('📤 Workout result:', JSON.stringify(result, null, 2));

            // Get workout count after creation to verify
            const workoutsAfter = await this.getWorkoutCount();
            console.log(`📋 Workouts after creation: ${workoutsAfter}`);

            return {
                success: true,
                workoutId: result.workoutId,
                data: result,
                workoutCountBefore: workoutsBefore,
                workoutCountAfter: workoutsAfter
            };

        } catch (error) {
            console.error('❌ Error creating workout with library:', error.message);
            return {
                success: false,
                error: error.message
            };
        }
    }

    /**
     * Get workout count using the library
     * @returns {Promise<number>} - Number of workouts
     */
    async getWorkoutCount() {
        if (!this.isAuthenticated || !this.client) {
            throw new Error('Not authenticated with Garmin Connect');
        }

        try {
            console.log('📋 Fetching workout count using library...');
            
            // Use the library's getWorkouts method
            const workouts = await this.client.getWorkouts(0, 100); // Get first 100 workouts
            console.log(`📋 Found ${workouts.length} workouts`);
            
            // Log details of recent workouts for debugging
            if (workouts.length > 0) {
                console.log('📋 Recent workouts:');
                workouts.slice(0, 3).forEach((workout, index) => {
                    console.log(`  ${index + 1}. ${workout.workoutName || 'Unnamed'} (ID: ${workout.workoutId})`);
                });
            }
            
            return workouts.length;
        } catch (error) {
            console.error('Error getting workout count with library:', error.message);
            return 0;
        }
    }

    /**
     * Test the authentication and basic API access using the library
     * @param {string} username - Garmin Connect username
     * @param {string} password - Garmin Connect password
     * @returns {Promise<Object>} - Test results
     */
    async testConnection(username, password) {
        const result = {
            authentication: false,
            apiAccess: false,
            userInfo: null,
            error: null
        };

        try {
            // Test authentication
            result.authentication = await this.authenticate(username, password);
            
            if (result.authentication) {
                // Test API access by getting user profile and workout count
                const userProfile = await this.client.getUserProfile();
                const workoutCount = await this.getWorkoutCount();
                
                result.apiAccess = true;
                result.userInfo = {
                    username: userProfile.userName || userProfile.displayName,
                    profileId: userProfile.profileId,
                    workoutCount: workoutCount
                };
                
                console.log('👤 User profile:', userProfile.userName || userProfile.displayName);
                console.log('📊 Workout count:', workoutCount);
            }

        } catch (error) {
            result.error = error.message;
            console.error('❌ Test connection failed:', error.message);
        }

        return result;
    }

    /**
     * Cleanup session
     */
    disconnect() {
        this.client = null;
        this.isAuthenticated = false;
        console.log('📴 Disconnected from Garmin Connect');
    }
}

module.exports = GarminConnectService;

module.exports = GarminConnectService;
